"""
AI Chat Assistant — V1
Converts natural-language questions into SQL, queries DuckDB, and returns answers.
"""
from google import genai
import os
import re
import logging
import json
from typing import Dict, Any, Optional, List
from utils.anonymizer import anonymize_data, restore_pii
from data_engine.sheets_handler import get_sheets_handler

logger = logging.getLogger(__name__)

# Initialize GenAI Client
client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

# ─── PII Configuration ───────────────────────────────────────────
# Common PII column names found in the database/metadata
PII_COLUMNS = ['organizationName', 'user_id', 'email', 'user_pseudo_id', 'organization_id']

# ─── Schema Cache ────────────────────────────────────────────────
_schema_cache: Optional[str] = None


def get_schema_context() -> str:
    """
    Query DuckDB for all table names and their column schemas.
    Caches the result for the lifetime of the process.
    """
    global _schema_cache
    if _schema_cache:
        return _schema_cache

    from data_engine.data_loader import get_data_loader
    loader = get_data_loader()

    try:
        tables = loader.con.execute("SHOW TABLES").fetchall()
        schema_parts = []
        for (table_name,) in tables:
            if table_name.startswith('_'):
                continue  # skip internal metadata tables
            cols = loader.con.execute(f"DESCRIBE {table_name}").fetchall()
            col_descs = ", ".join([f"{c[0]} ({c[1]})" for c in cols])
            schema_parts.append(f"  • {table_name}: {col_descs}")
        
        _schema_cache = "\n".join(schema_parts)
        logger.info(f"Schema context built: {len(schema_parts)} tables discovered.")
        return _schema_cache
    except Exception as e:
        logger.error(f"Failed to build schema context: {e}")
        return "(schema unavailable)"


def _extract_sql(text: str) -> Optional[str]:
    """Extract SQL from a code-fenced response."""
    match = re.search(r"```sql\s*(.*?)\s*```", text, re.DOTALL | re.IGNORECASE)
    if match:
        return match.group(1).strip()
    # Fallback: if the entire response looks like SQL
    stripped = text.strip()
    if stripped.upper().startswith("SELECT"):
        return stripped
    return None


def _is_safe_sql(sql: str) -> bool:
    """Reject any SQL that is not a SELECT."""
    dangerous = ['INSERT', 'UPDATE', 'DELETE', 'DROP', 'ALTER', 'CREATE', 'TRUNCATE', 'REPLACE']
    upper = sql.upper().strip()
    for keyword in dangerous:
        if re.search(rf'\b{keyword}\b', upper):
            logger.warning(f"Blocked dangerous SQL keyword: {keyword}")
            return False
    return True


def ask(question: str) -> Dict[str, Any]:
    """
    Main entry point: NLP question → SQL → DuckDB query → natural-language answer.
    
    Returns:
        {
            "answer": str,          # Natural-language summary
            "sql": str | None,      # The generated SQL
            "data": list[dict] | None,  # Up to 20 result rows
            "error": str | None     # Error message if something failed
        }
    """
    logger.info(f"Chat assistant received question: '{question[:80]}...'")
    
    schema = get_schema_context()
    
    # ── Step 1: Generate SQL ──────────────────────────────────────
    sql_prompt = f"""
You are a data analyst assistant. You have access to a DuckDB database with the following tables and columns:

{schema}

The user asks a question in plain English. Your job:
1. Write a single SQL SELECT query that answers the question.
2. Wrap the SQL in a ```sql``` code fence.
3. After the SQL, write a one-sentence explanation of what the query does.

Rules:
- Only use SELECT statements. Never write INSERT, UPDATE, DELETE, DROP, etc.
- Only reference tables and columns listed above.
- Use DuckDB SQL dialect.
- If the question cannot be answered with the available tables, say so clearly and do not generate SQL.
- Keep queries simple and efficient.

User question: {question}
""".strip()

    try:
        logger.debug("Sending question to LLM for SQL generation...")
        sql_response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=sql_prompt
        )
        raw_response = sql_response.text.strip()
        logger.debug(f"LLM SQL response received ({len(raw_response)} chars)")
        
        sql = _extract_sql(raw_response)
        
        if not sql:
            # The LLM couldn't generate SQL — return its explanation directly
            logger.info("No SQL generated by LLM — returning explanation.")
            return {
                "answer": raw_response.replace("```", "").strip(),
                "sql": None,
                "data": None,
                "error": None
            }
        
        if not _is_safe_sql(sql):
            return {
                "answer": "I can only run read-only queries. Your request appears to modify data, which I cannot do.",
                "sql": sql,
                "data": None,
                "error": "Blocked: non-SELECT SQL detected."
            }
        
        # ── Step 2: Execute SQL ───────────────────────────────────
        logger.info(f"Executing generated SQL: {sql[:120]}...")
        from data_engine.data_loader import get_data_loader
        loader = get_data_loader()
        
        df = loader.execute_query(sql)
        
        if df is None or df.empty:
            return {
                "answer": "The query returned no results. Try rephrasing your question or checking if data is available.",
                "sql": sql,
                "data": None,
                "error": None
            }
        
        # Limit rows for display and LLM summarization
        row_count = len(df)
        display_df = df.head(20)
        
        # ── Step 2.5: PII Protection ─────────────────────────────
        # Convert to records for checking PII
        data_for_display = display_df.to_dict(orient='records')
        
        # Check if the result contains any PII columns
        found_pii = [col for col in display_df.columns if col in PII_COLUMNS]
        pii_mapping = {}
        
        if found_pii:
            logger.info(f"PII columns detected in query result: {found_pii}. Anonymizing.")
            anonymized_records, pii_mapping = anonymize_data(data_for_display, found_pii)
            # Use anonymized records for the LLM summary
            summary_data_text = json.dumps(anonymized_records, indent=1)
        else:
            summary_data_text = display_df.to_string(index=False)

        logger.info(f"Query returned {row_count} rows. Sending top {len(display_df)} to LLM for summary.")
        
        # ── Step 3: Summarize results ────────────────────────────
        summary_prompt = f"""
You are a helpful data analyst. The user asked: "{question}"

The SQL query returned the following data ({row_count} total rows, showing top {len(display_df)}):
{summary_data_text}

Write a concise, plain-English answer (2-4 sentences max) that directly answers the user's question based on this data. 
Be specific with numbers. Do not use markdown formatting. Do not mention SQL or databases.
**Privacy Notice**: If you see values starting with "HIDDEN_", these are anonymized unique identifiers. Refer to them naturally as "Organization [Identifier]" or similar.
""".strip()

        summary_response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=summary_prompt
        )
        answer = summary_response.text.strip()
        
        # ── Step 4: Final Restoration & Logging ─────────────────
        # Restore PII in the natural language answer
        if pii_mapping:
            logger.info("Restoring hashes in AI natural language answer.")
            answer = restore_pii(answer, pii_mapping)
        
        tokens_used = 0
        try:
             tokens_used = summary_response.usage_metadata.total_token_count
        except:
             pass

        # Log to Google Sheets
        try:
            sheets = get_sheets_handler()
            sheets.log_interaction(
                user_input=question,
                sql=sql,
                data=data_for_display,
                output=answer,
                tokens=tokens_used
            )
        except Exception as sheet_err:
            logger.error(f"Failed to log to Google Sheets: {sheet_err}")

        logger.debug("Summary generated and logged successfully.")
        
        return {
            "answer": answer,
            "sql": sql,
            "data": data_for_display,
            "error": None
        }
        
    except Exception as e:
        logger.error(f"Chat assistant error: {e}")
        return {
            "answer": "I encountered an error processing your question. Please try again.",
            "sql": None,
            "data": None,
            "error": str(e)
        }
